name: First workflow

on: push

jobs:
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:
        - name: Step One Job One
          uses: actions/checkout@v2
        - name: Step Two Job One
          run: env | sort
        
    job2:
        name: Second job
        runs-on: windows-latest
        steps:
        - name: Step One Job Two
          uses: actions/checkout@v2
        - name: Step Two Job Two
          run: "Get-ChildItem Env: | Sort-Object Name"